# Generated by Django 5.2.4 on 2025-07-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='submission_id',
        ),
        migrations.AddField(
            model_name='useranswer',
            name='name',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
