# Generated by Django 5.2.4 on 2025-07-24 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_useranswer_submission_id_useranswer_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAnswer',
        ),
    ]
