# Generated by Django 5.2.4 on 2025-07-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_participant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Participant',
        ),
        migrations.AddField(
            model_name='question',
            name='choice_a',
            field=models.CharField(default='Not provided', max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='choice_b',
            field=models.CharField(default='Not provided', max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='choice_c',
            field=models.CharField(default='Not provided', max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='choice_d',
            field=models.CharField(default='Not provided', max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_choice',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(),
        ),
    ]
