# Generated by Django 5.2.4 on 2025-07-24 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_quizresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuizResult',
        ),
    ]
